# Generated by Django 4.2.21 on 2025-06-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatworkRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SKUConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=30)),
                ('data_month', models.CharField(max_length=7)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('jan_code', models.CharField(blank=True, max_length=13, null=True)),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sales_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('secure_days', models.IntegerField(default=30)),
                ('delivery_days', models.IntegerField(default=45)),
                ('amazon_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shipping_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('storage_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('profit_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('minimum_profit_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_target', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_inventory', models.IntegerField(default=0)),
                ('asin', models.CharField(blank=True, max_length=10, null=True)),
                ('last_sales_sync', models.DateTimeField(blank=True, null=True)),
                ('daily_sales_estimate', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
            ],
            options={
                'ordering': ['sku', '-data_month'],
                'unique_together': {('sku', 'data_month')},
            },
        ),
    ]
