# Generated by Django 4.2.23 on 2025-06-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logex_web_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skuconfig',
            name='other_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
