# Generated by Django 4.2.23 on 2025-08-27 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logex_web_app', '0002_skuconfig_other_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatworkroom',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatwork_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skuconfig',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sku_configs', to=settings.AUTH_USER_MODEL),
        ),
    ]
